version: "2"

services:
  grafana:
    image: grafana/grafana
    restart: always
    expose:
      - "3000"
    external_links:
      - prometheus
    environment:
      GF_INSTALL-PLUGINS: grafana-clock-panel, grafana-simple-json-datasource
      VIRTUAL_HOST: grafana.bgms.store
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: grafana.bgms.store
    networks:
      - webproxy
      - default

networks:
  webproxy:
    external:
      name: webproxy
  default:
    external:
      name: kong_network
